 server:
  port: 9999
  servlet:
    context-path: /
    session:
        timeout: 30m
 spring:
  redis:
     host: 127.0.0.1
     port: 6379
     database: 0
     lettuce:
       shutdown-timeout: 2000ms
       pool:
         max-active: 7
         max-idle: 7
         min-idle: 2
         max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mywork?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
      date-format: yyyy-MM-dd
      joda-date-time-format: yyyy-MM-dd
      default-property-inclusion: ALWAYS
      time-zone: GMT+8
  resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    check-template: true
    cache: false
    check-template-location: true
    enabled: true
    encoding: utf-8
    suffix: .html
 mybatis-plus:
   # xml mapper 使用注解的方式就不能扫xml 目前使用的注解方式，注解和xml 两者只能选择其一
   mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*/*/*.xml,classpath:mapper/*/*/*.xml
   # 实体扫描，多个package用逗号或者分号分隔
   type-aliases-package: com.core.entity
   configuration:
     # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 files:
   path: ${file-path:d:/phone}

